### ISSUE TITLE
FmServer.get_db_names() , FmServer.get_layout_names() , FmServer.get_field_names() , FmServer.do_find({...}) not working with FM Server 19: Empty XML Error

### ISSUE THREAD

**Issue by MoZiegler** [jeremie-borel/pyfilemaker2#1]
We Updated our Filemaker Server from Version 18 to 19 and now the above functions of FmServer don't work anymore. I get an error

**lxml.etree.XMLSyntaxError: Document is empty, line 1, column 1**

on all of them. My code and error messages is in the word document.
[XML-API-fms19-error.docx](https://github.com/jeremie-borel/pyfilemaker2/files/7278140/XML-API-fms19-error.docx)

**Comment by AFarris01** [comment]
I can confirm this as well.  Recently looking at converting to python for a custom application which is using a Filemaker database as a source, and wanted to try this out.  With FMS 19+ all requests result in 'Document is empty' errors.

**Comment by jeremie-borel** [comment]
Hi, I don't have any FMS 19 at hand. Can someone post the xml response from a browser when the url

http://<myserver-hostname>/fmi/xml/fmresultset.xml?-dbnames

is visited on his server ? Anyway I will certainly have to look into this but maybe not before FMS 20 as we will probably stick to 18 until that point.

**Comment by jeremie-borel** [comment]
Ok. Got my hand on a fms19 server. The problem should be fixed with version 0.2.4
